---
title: "Test Drive: Drizzle ORM with Cloudflare D1"
description: "A minimal walkthrough of connecting Drizzle ORM to a Cloudflare D1 database inside a Hono Worker, covering setup, schema, migrations, and basic queries."
slug: "test-drive-drizzle-orm-with-cloudflare-d1"
date: "2026-06-22"
tags: ['Cloudflare', 'D1', 'Drizzle', 'Hono', 'TypeScript']
author: "Petrus Johannes Maas"
---

# Test Drive: Drizzle ORM with Cloudflare D1

## Overview

D1 is Cloudflare's SQLite-based relational database, accessible directly from a Worker via a binding. Drizzle ORM sits on top of that binding and gives you a type-safe query builder and schema management via `drizzle-kit`.

This guide creates a D1 database, connects it to a Hono Worker with Drizzle, defines a schema, runs a migration, and does a basic read and write.

### File layout

```
src/
  server/
    app.ts          # Hono app
    db/
      schema.ts     # Drizzle table definitions
      index.ts      # db instance factory
drizzle/
  migrations/       # generated by drizzle-kit
drizzle.config.ts   # drizzle-kit config
wrangler.jsonc      # Cloudflare Worker config
```

## 1. Install dependencies

```bash
npm install drizzle-orm hono
npm install -D drizzle-kit wrangler
```

## 2. Create the D1 database

```bash
npx wrangler d1 create my-db
```

Wrangler prints the `database_id` — copy it for the next step.

## 3. Configure Wrangler

`wrangler.jsonc`:

```jsonc
{
  "name": "my-worker",
  "main": "src/server/app.ts",
  "compatibility_date": "2026-06-22",
  "compatibility_flags": ["nodejs_compat"],
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "my-db",
      "database_id": "YOUR_DB_ID",
      "migrations_dir": "drizzle/migrations"
    }
  ]
}
```

`binding` is the name you'll use to access D1 from your Worker via `env.DB`. It can be anything — `DB` is the convention.

## 4. Configure Drizzle Kit

`drizzle.config.ts`:

```ts
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  dialect: 'sqlite',
  schema: './src/server/db/schema.ts',
  out: './drizzle/migrations',
  driver: 'd1-http',
  dbCredentials: {
    accountId: process.env.CLOUDFLARE_ACCOUNT_ID!,
    databaseId: process.env.CLOUDFLARE_DATABASE_ID!,
    token: process.env.CLOUDFLARE_D1_TOKEN!,
  },
});
```

For local development you won't need the credentials — `drizzle-kit generate` just reads your schema and writes SQL files. The credentials are only needed if you run `drizzle-kit migrate` against the remote database directly. For local work, use Wrangler to apply migrations (see step 6).

## 5. Define a schema

`src/server/db/schema.ts`:

```ts
import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
});
```

## 6. Generate and apply the migration

Generate the SQL migration file from your schema:

```bash
npx drizzle-kit generate
```

Apply it locally against your D1 database:

```bash
npx wrangler d1 migrations apply my-db --local
```

Drop `--local` to apply against the remote D1 database.

## 7. Create the db instance

`src/server/db/index.ts`:

```ts
import { drizzle } from 'drizzle-orm/d1';
import { users } from './schema';

export { users };

export function createDb(d1: D1Database) {
  return drizzle(d1);
}
```

`D1Database` is the type Cloudflare injects for the binding. `drizzle()` wraps it and returns a fully typed query builder.

## 8. Wire it into Hono

`src/server/app.ts`:

```ts
import { Hono } from 'hono';
import { createDb, users } from './db/index';

type Bindings = {
  DB: D1Database;
};

const app = new Hono<{ Bindings: Bindings }>();

app.get('/users', async (c) => {
  const db = createDb(c.env.DB);
  const result = await db.select().from(users).all();
  return c.json(result);
});

app.post('/users', async (c) => {
  const { name, email } = await c.req.json();
  const db = createDb(c.env.DB);
  await db.insert(users).values({ name, email });
  return c.json({ status: 'ok' });
});

export default app;
```

`c.env.DB` is how Hono exposes the `DB` binding declared in `wrangler.jsonc`. The `Bindings` type makes this fully type-safe — TypeScript knows `c.env.DB` is a `D1Database`.

## 9. Run locally

```bash
npx wrangler dev
```

In another terminal:

```bash
# insert a user
curl -X POST http://localhost:8787/users \
  -H 'Content-Type: application/json' \
  -d '{"name":"Petrus","email":"petrus@example.com"}'

# read all users
curl http://localhost:8787/users
```

## 10. Deploy

```bash
npx wrangler deploy

# apply migrations to the remote database
npx wrangler d1 migrations apply my-db
```

## Where to go from here

- Add more tables to `src/server/db/schema.ts` and re-run `drizzle-kit generate` + `migrations apply` for each change
- Use `db.select().from(users).where(eq(users.email, email))` for filtered queries — all type-safe
- Add Zod validation on the POST body (see the Zod middleware guide) before the insert
- Use `db.batch([...])` to run multiple statements in a single round trip, which matters on Workers where latency per request is tight

**Disclaimer & Intent**:
This project was developed for research and portfolio purposes. The
primary goal is to explore architectural patterns and software systems.
It is provided for educational and demonstration purposes.

**License**:
Copyright © 2026 [Petrus Johannes Maas](https://github.com/petrusjohannesmaas)
Licensed under the Apache License, Version 2.0. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0

**Third-Party Attribution**:
All included dependencies and libraries are the property of their respective owners and are used according to their original licensing terms.
